# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5116

# Company APIS
## POST /api/Companies
## GET /api/Companies
## GET /api/Companies/{companyID}
## GET /api/Companies?pageSize=2&pageIndex=3
## PUT /api/Companies/{companyID}
## DELETE /api/Companies/{companyID} ( Delete employees uner this company in same time )


## AC1 Create Company API 
POST https://{{hostname}}:{{port}}/api/companies
Content-Type: application/json; charset=utf-8

{
  "name": "Google"
}

## Response:
### Case1:  Company Created Success, Return Company created with Status Created( 201 )
### Case2:  Company Name Exsiting, Return 400 Bad request
### Case3:  Other Bad Reqeust ( Request Body Not Valid )

######################################################################################

## AC2 Get All Compaines
GET https://{{hostname}}:{{port}}/api/companies

### Response: OK 200 with List of Companes

######################################################################################

## AC3 Get Company By ID
GET https://{{hostname}}:{{port}}/api/Companies/{companyID}

### Response: 
### Case1: OK 200 with The Company Found
### Case2: 404 Company NOT Found

## AC4 GET Companies with Paging 
GET https://{{hostname}}:{{port}}/api/Companies?pageSize=2&pageIndex=3
### Response: OK 200 with List of Companes

######################################################################################

## AC5 Update Company 
PUT https://{{hostname}}:{{port}}/api/Companies/{companyID}
Content-Type: application/json; charset=utf-8

{
  "name": Google
}
### Response: 
### Case1: Sucess, 204 NO Content
### Case2: 404 Company NOT Found

######################################################################################

## AC6 Add an employee to a specific company
Post https://{{hostname}}:{{port}}/api/Companies/{companyID}/employees
Content-Type: application/json; charset=utf-8

{
  "name": "Alice"
  "companyId":"xxxxxxxxxxxxxxxxx"
}
### Response: 
### Case1:  Employee Created Success, Return Employee created with Status Created( 201 )
### Case2:  Employee Name Exsiting in this specific company, Return 400 Bad request
### Case3:  Other Bad Reqeust ( Request Body Not Valid )

######################################################################################

## AC7 Delete an employee to a specific company
Delete https://{{hostname}}:{{port}}/api/Companies/{companyID}/{employeeID}
Content-Type: application/json; charset=utf-8

{
  "employeeID": "xxxxxxxxxxxxxxxxxxxxxx"
}
### Response: 
### Case1:  Employee deleted Success, Return Employee deleted with Status (204 )
### Case2:  EmployeeId Not Existing, Return 404
### Case3:  Other Bad Reqeust ( Request Body Not Valid )

######################################################################################

## AC8 Obtain list of all employee under a specific company
Get https://{{hostname}}:{{port}}/api/Companies/{companyID}/employees
Content-Type: application/json; charset=utf-8
### Response: 
### Case1:  Response: OK 200 with List of Employees of a specific company:

######################################################################################


## AC9 Update Basic information of a specifi employee under a specific company
PUT https://{{hostname}}:{{port}}/api/Companies/{companyID}/{employeeID}
Content-Type: application/json; charset=utf-8

{
  ["employeeId":"xxxxxxxxxxxxxxxxx",
  "employeeName":"Alice"
  "companyId":"xxxxxxxxxxxxxx"
  ],
    ["employeeId":"xxxxxxxxxxxxxxxxx",
  "employeeName":"Bob"
  "companyId":"xxxxxxxxxxxxxx"
  ]
}
### Response: 
### Case1:  Response: OK 200 with LUpdate Basic information of a specifi employee under a specific company
### Case2:  EmployeeId or CompanyId Not Existing, Return 404
### Case3:  Other Bad Reqeust ( Request Body Not Valid )

######################################################################################

## AC10 Delete a specific company with all employess belong to Company Deleted
PUT https://{{hostname}}:{{port}}/api/Companies/{companyID}
Content-Type: application/json; charset=utf-8

{
  "companyId":"xxxxxxxxxxxxxxx"
}
### Response: 
### Case1:  Response:  Ecompany with all employess belong to Company Success, Return Employee deleted with Status (204 )
### Case2:  CompanyId Not Existing, Return 404
### Case3:  Other Bad Reqeust ( Request Body Not Valid )

######################################################################################